
services:
  postgres:
    image: postgres:16
    container_name: speedrun_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: speedrun_admin
      POSTGRES_PASSWORD: speedrun_pass
      POSTGRES_DB: speedrun_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: speedrun_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  airflow-db:
    image: postgres:16
    container_name: airflow_metadata_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.3
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create --username admin --password admin --firstname Rashini --lastname D --role Admin --email admin@example.com
    volumes:
      - ./dags:/opt/airflow/dags
      - ./extract:/opt/airflow/extract
      - ./sql:/opt/airflow/sql

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow_webserver
    restart: unless-stopped
    depends_on:
      - airflow-db
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./extract:/opt/airflow/extract
      - ./sql:/opt/airflow/sql
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow_scheduler
    restart: unless-stopped
    depends_on:
      - airflow-db
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./extract:/opt/airflow/extract
      - ./sql:/opt/airflow/sql
    command: scheduler

volumes:
  postgres_data:
  airflow_db_data: